[2025-05-28T05:17:48.239+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T05:17:48.323+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [queued]>
[2025-05-28T05:17:48.390+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [queued]>
[2025-05-28T05:17:48.390+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-05-28T05:17:48.494+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_street_food_analysis> on 2025-05-28 05:01:59.929994+00:00
[2025-05-28T05:17:48.502+0000] {standard_task_runner.py:72} INFO - Started process 169 to run task
[2025-05-28T05:17:48.510+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'global_street_food_analysis_dag', 'run_street_food_analysis', 'manual__2025-05-28T05:01:59.929994+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/global_food.py', '--cfg-path', '/tmp/tmp8ji2lq8y']
[2025-05-28T05:17:48.513+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask run_street_food_analysis
[2025-05-28T05:17:48.593+0000] {task_command.py:467} INFO - Running <TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [running]> on host 6041824b4dd1
[2025-05-28T05:17:48.765+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='global_street_food_analysis_dag' AIRFLOW_CTX_TASK_ID='run_street_food_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:01:59.929994+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:01:59.929994+00:00'
[2025-05-28T05:17:48.768+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T05:17:48.894+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-28T05:17:48.895+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/food.py']
[2025-05-28T05:17:48.921+0000] {subprocess.py:86} INFO - Output:
[2025-05-28T05:18:05.231+0000] {subprocess.py:93} INFO - 25/05/28 05:18:05 INFO SparkContext: Running Spark version 3.5.5
[2025-05-28T05:18:05.236+0000] {subprocess.py:93} INFO - 25/05/28 05:18:05 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:18:05.247+0000] {subprocess.py:93} INFO - 25/05/28 05:18:05 INFO SparkContext: Java version 17.0.15
[2025-05-28T05:18:05.735+0000] {subprocess.py:93} INFO - 25/05/28 05:18:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-28T05:18:06.433+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceUtils: ==============================================================
[2025-05-28T05:18:06.435+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-28T05:18:06.444+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceUtils: ==============================================================
[2025-05-28T05:18:06.449+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SparkContext: Submitted application: GlobalStreetFoodAnalysis
[2025-05-28T05:18:06.613+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-28T05:18:06.652+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceProfile: Limiting resource is cpu
[2025-05-28T05:18:06.654+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-28T05:18:06.933+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SecurityManager: Changing view acls to: airflow
[2025-05-28T05:18:06.934+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-28T05:18:06.936+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SecurityManager: Changing view acls groups to:
[2025-05-28T05:18:06.937+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SecurityManager: Changing modify acls groups to:
[2025-05-28T05:18:06.938+0000] {subprocess.py:93} INFO - 25/05/28 05:18:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-05-28T05:18:09.096+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO Utils: Successfully started service 'sparkDriver' on port 41605.
[2025-05-28T05:18:09.364+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO SparkEnv: Registering MapOutputTracker
[2025-05-28T05:18:09.671+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-28T05:18:09.833+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-28T05:18:09.834+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-28T05:18:09.866+0000] {subprocess.py:93} INFO - 25/05/28 05:18:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-28T05:18:10.347+0000] {subprocess.py:93} INFO - 25/05/28 05:18:10 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-169f3148-47f6-440a-8fe6-04015d64ce4e
[2025-05-28T05:18:10.476+0000] {subprocess.py:93} INFO - 25/05/28 05:18:10 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-28T05:18:10.542+0000] {subprocess.py:93} INFO - 25/05/28 05:18:10 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-28T05:18:11.122+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-28T05:18:11.456+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-28T05:18:11.894+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Executor: Starting executor ID driver on host 6041824b4dd1
[2025-05-28T05:18:11.895+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:18:11.895+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Executor: Java version 17.0.15
[2025-05-28T05:18:11.904+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-28T05:18:11.906+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6a0c5f26 for default.
[2025-05-28T05:18:11.981+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43435.
[2025-05-28T05:18:11.981+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO NettyBlockTransferService: Server created on 6041824b4dd1:43435
[2025-05-28T05:18:11.995+0000] {subprocess.py:93} INFO - 25/05/28 05:18:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-28T05:18:12.011+0000] {subprocess.py:93} INFO - 25/05/28 05:18:12 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6041824b4dd1, 43435, None)
[2025-05-28T05:18:12.020+0000] {subprocess.py:93} INFO - 25/05/28 05:18:12 INFO BlockManagerMasterEndpoint: Registering block manager 6041824b4dd1:43435 with 434.4 MiB RAM, BlockManagerId(driver, 6041824b4dd1, 43435, None)
[2025-05-28T05:18:12.033+0000] {subprocess.py:93} INFO - 25/05/28 05:18:12 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6041824b4dd1, 43435, None)
[2025-05-28T05:18:12.036+0000] {subprocess.py:93} INFO - 25/05/28 05:18:12 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6041824b4dd1, 43435, None)
[2025-05-28T05:18:13.614+0000] {subprocess.py:93} INFO - 25/05/28 05:18:13 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-28T05:18:13.630+0000] {subprocess.py:93} INFO - 25/05/28 05:18:13 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp4805ln_0/spark-warehouse'.
[2025-05-28T05:18:23.867+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-28T05:18:23.868+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/food.py", line 10, in <module>
[2025-05-28T05:18:23.870+0000] {subprocess.py:93} INFO -     df = spark.read.csv("/home/sreelakshmi/pyspark_airflow/global_street_food.csv", header=True, inferSchema=True)
[2025-05-28T05:18:23.871+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-05-28T05:18:23.871+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-28T05:18:23.871+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-28T05:18:23.899+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/sreelakshmi/pyspark_airflow/global_street_food.csv.
[2025-05-28T05:18:24.025+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-28T05:18:24.029+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-28T05:18:24.049+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO SparkUI: Stopped Spark web UI at http://6041824b4dd1:4040
[2025-05-28T05:18:24.067+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-28T05:18:24.088+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO MemoryStore: MemoryStore cleared
[2025-05-28T05:18:24.088+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO BlockManager: BlockManager stopped
[2025-05-28T05:18:24.094+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-28T05:18:24.102+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-28T05:18:24.112+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO SparkContext: Successfully stopped SparkContext
[2025-05-28T05:18:24.113+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO ShutdownHookManager: Shutdown hook called
[2025-05-28T05:18:24.114+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-fd086715-6c59-45ac-80b3-b8a2d563fe4a
[2025-05-28T05:18:24.119+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-fd086715-6c59-45ac-80b3-b8a2d563fe4a/pyspark-2a622126-4741-44fa-9849-152190305ee9
[2025-05-28T05:18:24.125+0000] {subprocess.py:93} INFO - 25/05/28 05:18:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-fa09d666-a684-4f94-92e1-80a96a6c2b56
[2025-05-28T05:18:24.182+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-28T05:18:24.251+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:18:24.267+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=global_street_food_analysis_dag, task_id=run_street_food_analysis, run_id=manual__2025-05-28T05:01:59.929994+00:00, execution_date=20250528T050159, start_date=20250528T051748, end_date=20250528T051824
[2025-05-28T05:18:24.319+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T05:18:24.323+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task run_street_food_analysis (Bash command failed. The command returned a non-zero exit code 1.; 169)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:18:24.367+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-28T05:18:24.414+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
