[2025-05-28T05:02:02.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T05:02:02.251+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [queued]>
[2025-05-28T05:02:02.278+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [queued]>
[2025-05-28T05:02:02.279+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-05-28T05:02:02.316+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_street_food_analysis> on 2025-05-28 05:01:59.929994+00:00
[2025-05-28T05:02:02.327+0000] {standard_task_runner.py:72} INFO - Started process 507 to run task
[2025-05-28T05:02:02.331+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'global_street_food_analysis_dag', 'run_street_food_analysis', 'manual__2025-05-28T05:01:59.929994+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/global_food.py', '--cfg-path', '/tmp/tmpm1jatpxo']
[2025-05-28T05:02:02.334+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask run_street_food_analysis
[2025-05-28T05:02:02.567+0000] {task_command.py:467} INFO - Running <TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:01:59.929994+00:00 [running]> on host 96c1916b9317
[2025-05-28T05:02:02.848+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='global_street_food_analysis_dag' AIRFLOW_CTX_TASK_ID='run_street_food_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:01:59.929994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:01:59.929994+00:00'
[2025-05-28T05:02:02.851+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T05:02:02.910+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-28T05:02:02.923+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/food.py']
[2025-05-28T05:02:02.948+0000] {subprocess.py:86} INFO - Output:
[2025-05-28T05:02:03.012+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-28T05:02:11.262+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO SparkContext: Running Spark version 3.5.5
[2025-05-28T05:02:11.279+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:02:11.280+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO SparkContext: Java version 17.0.15
[2025-05-28T05:02:11.556+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-28T05:02:11.930+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceUtils: ==============================================================
[2025-05-28T05:02:11.931+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-28T05:02:11.938+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceUtils: ==============================================================
[2025-05-28T05:02:11.939+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO SparkContext: Submitted application: GlobalStreetFoodAnalysis
[2025-05-28T05:02:11.976+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-28T05:02:11.989+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceProfile: Limiting resource is cpu
[2025-05-28T05:02:11.990+0000] {subprocess.py:93} INFO - 25/05/28 05:02:11 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-28T05:02:12.106+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SecurityManager: Changing view acls to: airflow
[2025-05-28T05:02:12.107+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-28T05:02:12.107+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SecurityManager: Changing view acls groups to:
[2025-05-28T05:02:12.107+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SecurityManager: Changing modify acls groups to:
[2025-05-28T05:02:12.108+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-05-28T05:02:12.598+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO Utils: Successfully started service 'sparkDriver' on port 39171.
[2025-05-28T05:02:12.671+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SparkEnv: Registering MapOutputTracker
[2025-05-28T05:02:12.747+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-28T05:02:12.788+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-28T05:02:12.789+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-28T05:02:12.794+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-28T05:02:12.857+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-63fff4d0-bc66-413b-a55d-a491175c35f5
[2025-05-28T05:02:12.880+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-28T05:02:12.908+0000] {subprocess.py:93} INFO - 25/05/28 05:02:12 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-28T05:02:13.338+0000] {subprocess.py:93} INFO - 25/05/28 05:02:13 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-28T05:02:13.589+0000] {subprocess.py:93} INFO - 25/05/28 05:02:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-28T05:02:14.094+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Executor: Starting executor ID driver on host 96c1916b9317
[2025-05-28T05:02:14.094+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:02:14.095+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Executor: Java version 17.0.15
[2025-05-28T05:02:14.109+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-28T05:02:14.109+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5440f362 for default.
[2025-05-28T05:02:14.181+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36381.
[2025-05-28T05:02:14.182+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO NettyBlockTransferService: Server created on 96c1916b9317:36381
[2025-05-28T05:02:14.195+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-28T05:02:14.230+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96c1916b9317, 36381, None)
[2025-05-28T05:02:14.245+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO BlockManagerMasterEndpoint: Registering block manager 96c1916b9317:36381 with 434.4 MiB RAM, BlockManagerId(driver, 96c1916b9317, 36381, None)
[2025-05-28T05:02:14.249+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96c1916b9317, 36381, None)
[2025-05-28T05:02:14.258+0000] {subprocess.py:93} INFO - 25/05/28 05:02:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96c1916b9317, 36381, None)
[2025-05-28T05:02:16.372+0000] {subprocess.py:93} INFO - 25/05/28 05:02:16 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-28T05:02:16.404+0000] {subprocess.py:93} INFO - 25/05/28 05:02:16 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp8is60bni/spark-warehouse'.
[2025-05-28T05:02:21.944+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-28T05:02:21.945+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/food.py", line 10, in <module>
[2025-05-28T05:02:21.945+0000] {subprocess.py:93} INFO -     df = spark.read.csv("/home/sreelakshmi/pyspark_airflow/global_street_food.csv", header=True, inferSchema=True)
[2025-05-28T05:02:21.945+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-05-28T05:02:21.946+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-28T05:02:21.946+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-28T05:02:21.974+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/sreelakshmi/pyspark_airflow/global_street_food.csv.
[2025-05-28T05:02:22.137+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-28T05:02:22.138+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-28T05:02:22.157+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO SparkUI: Stopped Spark web UI at http://96c1916b9317:4040
[2025-05-28T05:02:22.198+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-28T05:02:22.246+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO MemoryStore: MemoryStore cleared
[2025-05-28T05:02:22.246+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO BlockManager: BlockManager stopped
[2025-05-28T05:02:22.257+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-28T05:02:22.269+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-28T05:02:22.322+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO SparkContext: Successfully stopped SparkContext
[2025-05-28T05:02:22.323+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO ShutdownHookManager: Shutdown hook called
[2025-05-28T05:02:22.323+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-7e7b9a3d-783f-489d-b4b7-4a34dd723a3b
[2025-05-28T05:02:22.357+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-7e7b9a3d-783f-489d-b4b7-4a34dd723a3b/pyspark-4997d86e-fb71-4bf6-a2dd-963cbcb00ff4
[2025-05-28T05:02:22.371+0000] {subprocess.py:93} INFO - 25/05/28 05:02:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-19f655ff-1c03-4500-85f6-86ae9f5d9c58
[2025-05-28T05:02:22.439+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-28T05:02:22.618+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:02:22.684+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=global_street_food_analysis_dag, task_id=run_street_food_analysis, run_id=manual__2025-05-28T05:01:59.929994+00:00, execution_date=20250528T050159, start_date=20250528T050202, end_date=20250528T050222
[2025-05-28T05:02:22.787+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T05:02:22.791+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task run_street_food_analysis (Bash command failed. The command returned a non-zero exit code 1.; 507)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:02:22.869+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-28T05:02:22.941+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T05:02:22.944+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
